on:
  workflow_call:
    inputs:
      # version:
      #   type: string
      #   required: true
      path:
        type: string
        required: true
jobs:
  commit:
    runs-on: ubuntu-22.04 
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.path }}
          pattern: "*_test.txt"
          merge-multiple: true

      - name: Git Status
        run: |
          git status
          echo "\n"
          echo "${{ inputs.path }}"

      - name: Commit Changes
        id: commit-changes
        env:
          commit_message: Automatic Commit via Workflows
          commit_author: antonycas
        run: |
          status=$(git status -s)
          path="${{ inputs.path }}"

          if grep -q "$path" <<< "$status"; then
            git config user.name "${{ env.commit_author }}"
            git config user.email "antonycas@users.noreply.github.com"
            git add "${{ inputs.path }}"
            git commit -m "${{ env.commit_message }}"
            git push
          else
            echo "No Changes made to ${{ inputs.path }} directory."
          fi