name: Test Commit
on: ['push']
jobs:
  commit:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Create file
        run: touch ai/cache/branch_test.txt

      - name: Display Status
        run: git status -s

      # - name: Set Commit Variable
      #   id: set-commit-variable
      #   run: |
      #     status=$(git status -s)
      #     file="ai/cache/branch_test.txt"
      #     if grep -q "$file" <<< "$status"; then
      #       echo "needs-commit='true'" >> $GITHUB_OUTPUT
      #     else
      #       echo "needs-commit='false'" >> $GITHUB_OUTPUT
      #     fi
      #     echo "$status"
      
      - name: Commit changes
        id: commit-changes
        env:
          COMMIT_MESSAGE: Automatic Commit via Workflows
          COMMIT_AUTHOR: antonycas
        run: |
          status=$(git status -s)
          file="ai/cache/branch_test.txt"
          
          if grep -q "$file" <<< "$status"; then
            NEEDS-COMMIT="true"
          else
            NEEDS-COMMIT="false"
          fi

          if "$NEEDS-COMMIT" == "true"; then
            git config --global user.name "${{ env.COMMIT_AUTHOR }}"
            git config --global user.email "antonycas@users.noreply.github.com"
            git add ai/cache/branch_test.txt
            git commit -m "${{ env.COMMIT_MESSAGE }}"
            git push
          else
            echo "No updates were made"  
          fi
        # if: "${{ steps.set-commit-variable.outputs.needs-commit }}" == "true"


      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: "Antony Castineiras"
      #     author_email: "antony@cas.com"
      #     message: "Auto Commit via Worfklow"
      #     add: "ai/cache/test.txt"
      #   if: ${{ steps.set-commit-variable.outputs.needs-commit }} == "true"


      # - name: List git status
      #   id: list-git-status
      #   run: GIT_STATUS=$(git status -s ai/cache) && echo "git-status=$GIT_STATUS" >> $GITHUB_OUTPUT

      # - name: test file updated
      #   run: echo "Test file updated"
      #   if: ${{ 'ai/cache/test.txt' in  steps.list-git-status.outputs.git-status }}

      # - name: test file not updated
      #   run: echo "Test file updated"
      #   if: 'ai/cache/test.txt' not in ${{ steps.list-git-status.outputs.git-status }}

      # - name: echo git status
      #   run: echo ${{ steps.list-git-status.outputs.git-status }}
      