name: Test Commit
on:
  push:
    branches:
      - master
jobs:
  commit:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Create file
        run: touch ai/cache/test.txt

      - name: List git status
        id: list-git-status
        run: GIT_STATUS=$(git status -s ai/cache) && echo "git-status=$GIT_STATUS" >> $GITHUB_OUTPUT

      - name: test file updated
        run: echo "Test file updated"
        if: ${{ 'ai/cache/test.txt' in  steps.list-git-status.outputs.git-status }}

      # - name: test file not updated
      #   run: echo "Test file updated"
      #   if: 'ai/cache/test.txt' not in ${{ steps.list-git-status.outputs.git-status }}

      # - name: echo git status
      #   run: echo ${{ steps.list-git-status.outputs.git-status }}
      