name: Test Commit
on:
  push:
    branches:
      - master
jobs:
  commit:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Create file
        run: touch ai/cache/test.txt

      - name: List git status
        run: git status ai/cache